<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <_SuppressSdkImports>true</_SuppressSdkImports>

    <!--
      Adding NoWarn to remove build warnings
      NU1507: Warning when there are multiple package sources when using CPM with no source mapping
      NETSDK1201: Warning that specifying RID won't create self containing app
      PRI257: Ignore default language (en) not being one of the included resources (eg en-us, en-uk)
    -->
    <NoWarn>$(NoWarn);NU1507;NETSDK1201;PRI257</NoWarn>
  </PropertyGroup>

  <!-- See https://aka.platform.uno/using-uno-sdk#implicit-packages for more information regarding the Implicit Packages version properties. -->
  <PropertyGroup>
    <UnoExtensionsVersion>4.2.2</UnoExtensionsVersion> <!-- https://www.nuget.org/packages/Uno.Extensions.Core -->
    <UnoLoggingVersion>4.1.1</UnoLoggingVersion> <!-- https://www.nuget.org/packages/Uno.Core.Extensions.Logging -->
    <UnoResizetizerVersion>1.5.2</UnoResizetizerVersion> <!-- https://www.nuget.org/packages/Uno.Resizetizer -->
    <UnoToolkitVersion>6.1.8</UnoToolkitVersion> <!-- https://www.nuget.org/packages/Uno.Toolkit -->
    <UnoThemesVersion>5.1.7</UnoThemesVersion> <!-- https://www.nuget.org/packages/Uno.Themes -->
    <UnoUniversalImageLoaderVersion>1.9.37</UnoUniversalImageLoaderVersion> <!-- https://www.nuget.org/packages/Uno.UniversalImageLoader -->
    <UnoWasmBootstrapVersion>9.0.0-dev.104</UnoWasmBootstrapVersion> <!-- https://www.nuget.org/packages/Uno.Wasm.Bootstrap -->
    <UnoCSharpMarkupVersion>5.2.14</UnoCSharpMarkupVersion>
  </PropertyGroup>
</Project>
